version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      # Install dependencies
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn add jest-junit
      - run:
          name: Run tests
          command: yarn run test --ci --runInBand --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ./test-results/

  test-java:
    docker:
      - image: cimg/android:2023.10  # Use the cimg/android image with SDK pre-installed
    working_directory: ~/project/android
    environment:
      ANDROID_HOME: /opt/android-sdk  # Set Android SDK location
      ANDROID_SDK_ROOT: /opt/android-sdk
      PATH: /opt/android-sdk/tools:/opt/android-sdk/tools/bin:/opt/android-sdk/platform-tools:$PATH  # Add SDK tools to PATH
    steps:
      - checkout:
          path: ~/project
      # Set SDK location in `local.properties`
      - run:
          name: Set Android SDK location in local.properties
          command: echo "sdk.dir=/opt/android-sdk" > android/local.properties
      # Run Gradle build
      - run:
          name: Run Gradle build
          command: ./gradlew build
      - store_test_results:
          path: build/test-results
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
      - store_artifacts:
          path: build/reports

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  build-and-test:
    jobs:
      - test-node
      - test-java
